#version: '3'
#
#services:
#  db:
#    image: postgres
#  web:
#    build: ""
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db



version: "2"
services:
  web:
    build: .
    ports:
      - "8000:8000"
