version: '3'

services:
  db:
    image: postgres
  web:
    build: ""
    command: python3 /bgjournal/bgjournal/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bg-journal
    ports:
      - "8000:8000"
    depends_on:
      - db
