# Generated by Django 2.1.7 on 2019-03-18 18:55

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(default=datetime.now(), editable=False),
            preserve_default=False,
        ),
    ]
