# Generated by Django 2.1.7 on 2019-03-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='expansion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Expansion'),
        ),
    ]
